### ISSUE TITLE
Request for new release . May be 0.3.1 

### ISSUE THREAD

**Issue by skyrocknroll** [mp911de/spinach#31]
We are affected by this issue https://github.com/mp911de/spinach/issues/30

It would be great if you make an release with the fix

**Comment by mp911de** [comment]
Hi, 
The upgrade to lettuce will be released as `1.0.0.Final`. In the meantime, it would be great having feedback for `1.0.0-SNAPSHOT`. It's available in the Sonatype OSS Snapshot repo.

**Comment by mp911de** [comment]
Short update from my side: Disque is neither dead nor alive. I'm a bit restrained about releasing another release for now. TBH, there's little traffic for this project and no news how disque will proceed.

As soon as disque moves forward, Spinach will move too.

**Comment by skyrocknroll** [comment]
Hi @mp911de Disque is alive and still supported by antirez. You can find more details here. https://github.com/antirez/disque/issues/190 . Here you can find the roadmap of redis 4.2 which contain disque as module.  https://gist.github.com/antirez/a3787d538eec3db381a41654e214b31d

**Comment by mp911de** [comment]
Thanks for the reply. I wasn't aware of the module migration for disque. The module raises the questions whether it makes sense at all providing a standalone client for disque or add just additional elements for request/response RESP handling. Another issue is locality imposed by queues because queues can be distributed and do not follow the Redis Cluster idea of slot hash binding.

However,  the module migration will impose changes to spinach that are currently not foreseeable.
